<a href="https://colab.research.google.com/github/YdoUcare-qm/LearningDeep/blob/main/IntrotoTensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0+cu121


### Tensors

In [29]:
scalar = torch.tensor(9)
scalar

tensor(9)

In [30]:
scalar.ndim

0

In [31]:
scalar.item()

9

In [32]:
vector = torch.tensor([1,2,3])
print(vector.ndim)
# print(vector.item())
# print(type(vector.item()))
vector.shape

1


torch.Size([3])

In [33]:
matrix = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(matrix.ndim)
# print(vector.item())
# print(type(vector.item()))
matrix.shape

2


torch.Size([3, 3])

In [34]:
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
print(TENSOR.ndim)
# print(vector.item())
# print(type(vector.item()))
TENSOR.shape

3


torch.Size([1, 3, 3])

In [35]:
TENSOR[0][1]

tensor([4, 5, 6])

In [36]:
RANDOM_TENSOR=torch.rand(3,3,3)
RANDOM_TENSOR

tensor([[[0.4925, 0.5588, 0.6561],
         [0.4153, 0.6149, 0.8924],
         [0.2128, 0.4898, 0.6363]],

        [[0.8217, 0.4116, 0.8525],
         [0.5240, 0.1017, 0.6125],
         [0.0053, 0.6347, 0.1230]],

        [[0.3773, 0.5700, 0.6656],
         [0.9114, 0.0194, 0.5969],
         [0.8871, 0.1067, 0.0011]]])

In [37]:
ZEROS = torch.zeros(4,4,4)
ZEROS

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [38]:
ONES = torch.ones(4,4,4)
ONES.dtype

torch.float32

In [39]:
ar=torch.arange(0,10,2)
ar

tensor([0, 2, 4, 6, 8])

In [40]:
zl = torch.zeros_like(ar)
zl

tensor([0, 0, 0, 0, 0])

### Tensor Datatypes

In [41]:
f = torch.tensor([1.0,2.0,3.0],
                dtype=torch.float16,   ##datatype of the tensor
                device="cpu",  ## device of the tensor
                requires_grad=False ##whether to track the gradient of tensors in operations
                )
g = f.type(torch.float32)
f*g

tensor([1., 4., 9.])

### Tensor Manipulation

- Addition
- Subtraction
- Multiplication
- Division
- Matrix Multiplication

In [42]:
t= torch.tensor([1,2,3])
t=t+10
t

tensor([11, 12, 13])

In [43]:
t= torch.tensor([1,2,3])
t=t*10
t

tensor([10, 20, 30])

In [44]:
t= torch.tensor([1,2,3])
t=t-10
t

tensor([-9, -8, -7])

In [45]:
t= torch.tensor([1,2,3])
t=t/10
t

tensor([0.1000, 0.2000, 0.3000])

In [46]:
t1= torch.tensor([1,2,3])
t2 = torch.tensor([4,5,6])
torch.mul(t1,t2) #or t1*t2

tensor([ 4, 10, 18])

#### Matrix Multiplication
- Element-wise
- matrix multiplication(dot product)

In [51]:
%%time
t= torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
t@t

CPU times: user 277 µs, sys: 959 µs, total: 1.24 ms
Wall time: 1.18 ms


tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [52]:
%%time
torch.matmul(t,t) #Faster than for-loop

CPU times: user 552 µs, sys: 41 µs, total: 593 µs
Wall time: 427 µs


tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [57]:
t1=torch.tensor([[4,4,4],[5,6,7]])
t2=torch.tensor([[4,4,6],[5,7,8]])
print(torch.mm( t1,t2.T))
print(torch.mm( t1.T,t2))


tensor([[ 56,  80],
        [ 86, 123]])
tensor([[41, 51, 64],
        [46, 58, 72],
        [51, 65, 80]])


### Aggregate functions

In [63]:
x= torch.arange(0,100,10)
print(x,x.dtype)
x=x.type(torch.float32)
print(x.max(),torch.max(x))
print(x.min(),torch.min(x))
print(x.mean(),torch.mean(x))
print(x.sum(),torch.sum(x))


tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]) torch.int64
tensor(90.) tensor(90.)
tensor(0.) tensor(0.)
tensor(45.) tensor(45.)
tensor(450.) tensor(450.)


In [64]:
print(x.argmax())
print(x.argmin())

tensor(9)
tensor(0)


- Reshaping
- View
- Stacking
- Squeezing
- Unsqueezing
- Permute

In [1]:
import torch
x= torch.arange(1,10)
print(x)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [2]:
y=x.reshape(3,3)
y

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [3]:
y.reshape(9,1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [4]:
z=y.view(1,9) #same as reshape but the tensor object is same
z,y

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]))

In [5]:
z[:,0]=5
z,y

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]),
 tensor([[5, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]))

In [6]:
x=torch.arange(1,10)
y=torch.arange(1,100,11)
z=torch.arange(1,1000,111)
x,y,z

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([ 1, 12, 23, 34, 45, 56, 67, 78, 89]),
 tensor([  1, 112, 223, 334, 445, 556, 667, 778, 889]))

In [7]:
a=torch.stack([x,y,z],dim=0)
b=torch.stack([x,y,z],dim=1)
c=torch.stack([x,y,z],dim=-1)
d=torch.stack([x,y,z],dim=-2)
a,b,c,d

(tensor([[  1,   2,   3,   4,   5,   6,   7,   8,   9],
         [  1,  12,  23,  34,  45,  56,  67,  78,  89],
         [  1, 112, 223, 334, 445, 556, 667, 778, 889]]),
 tensor([[  1,   1,   1],
         [  2,  12, 112],
         [  3,  23, 223],
         [  4,  34, 334],
         [  5,  45, 445],
         [  6,  56, 556],
         [  7,  67, 667],
         [  8,  78, 778],
         [  9,  89, 889]]),
 tensor([[  1,   1,   1],
         [  2,  12, 112],
         [  3,  23, 223],
         [  4,  34, 334],
         [  5,  45, 445],
         [  6,  56, 556],
         [  7,  67, 667],
         [  8,  78, 778],
         [  9,  89, 889]]),
 tensor([[  1,   2,   3,   4,   5,   6,   7,   8,   9],
         [  1,  12,  23,  34,  45,  56,  67,  78,  89],
         [  1, 112, 223, 334, 445, 556, 667, 778, 889]]))

In [24]:
p=torch.ones(1,1,2)
q=torch.squeeze(p)
r=torch.squeeze(q)
p,p.shape,q,q.shape,r,r.shape

(tensor([[[1., 1.]]]),
 torch.Size([1, 1, 2]),
 tensor([1., 1.]),
 torch.Size([2]),
 tensor([1., 1.]),
 torch.Size([2]))

In [30]:
torch.unsqueeze(p,dim=-1).shape

torch.Size([1, 1, 2, 1])

In [37]:
a=torch.randint(0,100,(2,3))
a

tensor([[77, 74, 26],
        [83, 28, 28]])

In [38]:
a.permute(1,0)

tensor([[77, 83],
        [74, 28],
        [26, 28]])

#### Indexing

In [39]:
a=torch.randint(0,1000,(5,6))
a

tensor([[485, 892, 525, 601, 456, 962],
        [422, 158, 536, 924, 999, 755],
        [737,  33, 528, 393, 420, 195],
        [ 84, 772, 275, 284, 268, 930],
        [241, 765, 530, 240, 927, 349]])

In [53]:
a[1][2]

tensor(536)

### From and To NumPy

In [55]:
import numpy as np
b=np.array([1,2,3])
b,b.dtype

(array([1, 2, 3]), dtype('int64'))

In [56]:
b=torch.from_numpy(b)
b,b.dtype

(tensor([1, 2, 3]), torch.int64)

In [57]:
b=b.numpy()
b,b.dtype

(array([1, 2, 3]), dtype('int64'))

### Reproducibility

In [58]:
a= torch.rand(3,3)
b= torch.rand(3,3)
a,b

(tensor([[0.2660, 0.9916, 0.6617],
         [0.7598, 0.0381, 0.5826],
         [0.5239, 0.5633, 0.6728]]),
 tensor([[0.8645, 0.6877, 0.8651],
         [0.4032, 0.4317, 0.0709],
         [0.0287, 0.6173, 0.9019]]))

In [60]:
RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED)
c=torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
d=torch.rand(3,4)
c,d,c==d

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]))

### Running Computations on GPU
- Use Google colab GPU

In [3]:
!nvidia-smi

Thu Jul 11 11:24:23 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   36C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [4]:
# checking gpu access
import torch
torch.cuda.is_available()

True

In [5]:
# Setting up device agnostic code
device= "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [7]:
torch.cuda.device_count()

1

In [9]:
# using tensors on gpu for faster computations
a= torch.tensor([1,2,3],device=device)
a,a.device

(tensor([1, 2, 3], device='cuda:0'), device(type='cuda', index=0))

In [13]:
# or convert device
a=torch.arange(0,10,dtype=torch.float32)
print(a,a.device)
a_gpu = a.to("cuda")
print(a_gpu,a_gpu.device)

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]) cpu
tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], device='cuda:0') cuda:0


In [17]:
%%time
torch.matmul(a,a)

CPU times: user 972 µs, sys: 0 ns, total: 972 µs
Wall time: 1.02 ms


tensor(285.)

In [18]:
%%time
torch.matmul(a_gpu,a_gpu)

CPU times: user 165 µs, sys: 0 ns, total: 165 µs
Wall time: 169 µs


tensor(285., device='cuda:0')

In [19]:
# if tensor is on GPU, can't convert it to numpy
a_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [20]:
# have to convert them to cpu first
a=a_gpu.cpu()
a=a.numpy()
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)