<a href="https://colab.research.google.com/github/YdoUcare-qm/LearningDeep/blob/main/Pytorch_workflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np
if torch.cuda.is_available():
  device=torch.device("cuda")
else:
  device=torch.device("cpu")
device

device(type='cpu')

In [3]:
x=torch.ones(6,requires_grad=True)
x

tensor([1., 1., 1., 1., 1., 1.], requires_grad=True)

In [4]:
y=x*2
y

tensor([2., 2., 2., 2., 2., 2.], grad_fn=<MulBackward0>)

In [5]:
z=y*y*2
z=z.mean()
z

tensor(8., grad_fn=<MeanBackward0>)

In [6]:
z.backward()

In [7]:
x.grad

tensor([2.6667, 2.6667, 2.6667, 2.6667, 2.6667, 2.6667])

In [8]:
y=x*2
y
y=y.mean()
y.backward()
y,x.grad

(tensor(2., grad_fn=<MeanBackward0>), tensor([3., 3., 3., 3., 3., 3.]))

In [9]:
w=torch.tensor(1.0,requires_grad=True)

x=torch.tensor(5.0)
y=torch.tensor(10.0)

y_hat=w*x
loss= (y-y_hat)**2

loss.backward()
w.grad

tensor(-50.)

## Gradient Descent Algorithm

#### Manual

In [21]:
x=np.array([1,2,3,4,5,6,7,8,9,10])
y=np.array([5,10,15,20,25,30,35,40,45,50])
x,y

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50]))

In [24]:
w=0
#forward pass
def forward(x):
  return w*x

def loss(y_hat):
  return 1/len(y_hat) * np.sum((y-y_hat)**2)

def gradient(y_hat):
  return 1/len(y_hat) * 2 * np.sum(y_hat-y)

n_iter=100
lr=1e-2
for epoch in range(n_iter):
  y_pred=forward(x)
  l=loss(y_pred)
  grad=gradient(y_pred)
  w-= lr * grad
  print(f'Epoch : {epoch + 1} Training Loss : {l:.3f} grad : {grad} updated weight : {w}')

Epoch : 1 Training Loss : 962.500 grad : -55.0 updated weight : 0.55
Epoch : 2 Training Loss : 762.396 grad : -48.95 updated weight : 1.0395
Epoch : 3 Training Loss : 603.894 grad : -43.5655 updated weight : 1.475155
Epoch : 4 Training Loss : 478.344 grad : -38.773295000000005 updated weight : 1.8628879500000002
Epoch : 5 Training Loss : 378.897 grad : -34.508232549999995 updated weight : 2.2079702755
Epoch : 6 Training Loss : 300.124 grad : -30.712326969499998 updated weight : 2.515093545195
Epoch : 7 Training Loss : 237.728 grad : -27.333971002855005 updated weight : 2.7884332552235502
Epoch : 8 Training Loss : 188.305 grad : -24.32723419254095 updated weight : 3.0317055971489597
Epoch : 9 Training Loss : 149.156 grad : -21.651238431361445 updated weight : 3.2482179814625742
Epoch : 10 Training Loss : 118.146 grad : -19.269602203911685 updated weight : 3.440914003501691
Epoch : 11 Training Loss : 93.584 grad : -17.1499459614814 updated weight : 3.6124134631165052
Epoch : 12 Training 

#### using backward() and requires_grad=True

In [46]:
x=torch.tensor([1,2,3,4,5,6,7,8,9,10],dtype=torch.float32)
y=torch.tensor([5,10,15,20,25,30,35,40,45,50],dtype=torch.float32)

w= torch.tensor(0.0,requires_grad=True,dtype=torch.float32)
x,y,w
#forward pass
def forward(x):
  return w*x

def loss(y_hat):
  return 1/len(y_hat) * torch.sum((y-y_hat)**2)

n_iter=10
lr=1e-2

for epoch in range(n_iter):
  y_pred=forward(x)

  l=loss(y_pred)

  l.backward()
  with torch.no_grad():
    w-=lr*w.grad
  w.grad.zero_()

  print(f'Epoch : {epoch + 1} Training Loss : {l:.3f} grad : {grad:.5f} updated weight : {w}')

Epoch : 1 Training Loss : 962.500 grad : -0.00054 updated weight : 3.8499999046325684
Epoch : 2 Training Loss : 50.916 grad : -0.00054 updated weight : 4.735499858856201
Epoch : 3 Training Loss : 2.693 grad : -0.00054 updated weight : 4.939165115356445
Epoch : 4 Training Loss : 0.142 grad : -0.00054 updated weight : 4.986008167266846
Epoch : 5 Training Loss : 0.008 grad : -0.00054 updated weight : 4.996781826019287
Epoch : 6 Training Loss : 0.000 grad : -0.00054 updated weight : 4.999259948730469
Epoch : 7 Training Loss : 0.000 grad : -0.00054 updated weight : 4.9998297691345215
Epoch : 8 Training Loss : 0.000 grad : -0.00054 updated weight : 4.999960899353027
Epoch : 9 Training Loss : 0.000 grad : -0.00054 updated weight : 4.999990940093994
Epoch : 10 Training Loss : 0.000 grad : -0.00054 updated weight : 4.999998092651367


#### optim and loss

In [47]:
import torch.nn as nn
import torch.optim as optim

In [70]:
x=torch.tensor([[1,2,3,4,5,6,7,8,9,10]],dtype=torch.float32).reshape(10,1)
y=torch.tensor([[5,10,15,20,25,30,35,40,45,50]],dtype=torch.float32).reshape(10,1)
w= torch.tensor(0.0,requires_grad=True,dtype=torch.float32)
x,y,w
#forward pass
def forward(x):
  return w*x
loss=nn.MSELoss()
optimizer=optim.SGD([w],lr=0.01)

n_iter=10
lr=1e-2

for epoch in range(n_iter):
  #forward pass
  y_pred=forward(x)

  l=loss(y,y_pred)
  l.backward()
  g=w.grad
  optimizer.step()
  optimizer.zero_grad()


  print(f'Epoch : {epoch + 1} Training Loss : {l:.6f} grad : {g:.5f} updated weight : {w}')



Epoch : 1 Training Loss : 962.500000 grad : -385.00000 updated weight : 3.8499999046325684
Epoch : 2 Training Loss : 50.916260 grad : -88.55001 updated weight : 4.735499858856201
Epoch : 3 Training Loss : 2.693472 grad : -20.36651 updated weight : 4.939165115356445
Epoch : 4 Training Loss : 0.142484 grad : -4.68429 updated weight : 4.986008167266846
Epoch : 5 Training Loss : 0.007537 grad : -1.07737 updated weight : 4.996781826019287
Epoch : 6 Training Loss : 0.000399 grad : -0.24780 updated weight : 4.999259948730469
Epoch : 7 Training Loss : 0.000021 grad : -0.05698 updated weight : 4.9998297691345215
Epoch : 8 Training Loss : 0.000001 grad : -0.01311 updated weight : 4.999960899353027
Epoch : 9 Training Loss : 0.000000 grad : -0.00301 updated weight : 4.999990940093994
Epoch : 10 Training Loss : 0.000000 grad : -0.00070 updated weight : 4.999998092651367


#### using nn module

In [88]:
x=torch.tensor([[1,2,3,4,5,6,7,8,9,10]],dtype=torch.float32).reshape(10,1)
y=torch.tensor([[5,10,15,20,25,30,35,40,45,50]],dtype=torch.float32).reshape(10,1)
model=nn.Linear(1,1)
print(f'initial parameters:')
for name,param in model.named_parameters():
  print(name," : ",param)
loss=nn.MSELoss()
optimizer=optim.SGD(model.parameters(),lr=0.01)

n_iter=10
lr=1e-2

for epoch in range(n_iter):
  #forward pass
  y_pred=model(x)

  l=loss(y,y_pred)
  l.backward()
  optimizer.step()
  optimizer.zero_grad()
  p=list(model.parameters())


  print(f'\nEpoch:{epoch + 1} Training Loss:{l:.3f} updated weight:{p}')


initial parameters:
weight  :  Parameter containing:
tensor([[-0.1799]], requires_grad=True)
bias  :  Parameter containing:
tensor([-0.4784], requires_grad=True)

Epoch:1 Training Loss:1060.480 updated weight:[Parameter containing:
tensor([[3.8613]], requires_grad=True), Parameter containing:
tensor([0.1009], requires_grad=True)]

Epoch:2 Training Loss:48.670 updated weight:[Parameter containing:
tensor([[4.7270]], requires_grad=True), Parameter containing:
tensor([0.2242], requires_grad=True)]

Epoch:3 Training Loss:2.247 updated weight:[Parameter containing:
tensor([[4.9125]], requires_grad=True), Parameter containing:
tensor([0.2497], requires_grad=True)]

Epoch:4 Training Loss:0.117 updated weight:[Parameter containing:
tensor([[4.9524]], requires_grad=True), Parameter containing:
tensor([0.2543], requires_grad=True)]

Epoch:5 Training Loss:0.019 updated weight:[Parameter containing:
tensor([[4.9611]], requires_grad=True), Parameter containing:
tensor([0.2545], requires_grad=True)]